### PR TITLE
Department Navigation

### LINKED ISSUE #67: Moving card from the complete column to the next table
There is no way for a card to move to the next table when it is in the complete column. How this exactly is implemented is still up for debate a bit. I was thinking maybe a check mark that appears on the card when it is in the complete column that allows the card to be moved to the next table. This is a check mark that would ultimately be hidden from view for a normal user.

Another easier option might be to have a separate page that only admins can access that displays the cards in the complete column ready to be moved to the next column.

Of course these are only thoughts and we can discuss how we think this should be implemented here.

### LINKED ISSUE #71: Admin Department Navigation
Give admins controls to navigate each department.

### PR DESCRIPTION
**Pull request by MorganNesbitt**
fixes #67 
fixes #71 
# Summary
- Fix cards disappearance when moving stages
- Add department navigation
## Ongoing Problems
- Navigating to complete stage. See #82

### CODE REVIEW

**Comment by allenduy** [comment]
#### Problem

Looks like there are some overlaps from features/department_navigation and features/server. Both have implemented the card disappearing from the complete column. From server, however, gives feedback to the user with a checkmark icon. However, both implementations have a small bug; when clicking on 'needs work' it either has no response to the user (in this case), or (in features/server's case) it gives the user a checkmark icon stating that it is complete.

#### Solution

So what may need to be done is:
- keep the check marks for user feedback that it was sent to next stage
- when clicking 'needs work', get reason for sending back, and confirm
- it should be obvious to the previous dept. that they need to update 
  - send to in progress or todo and append a `sent back from {{next dept or user}} for reason: {{input from reviewer}}` to the beginning of the card description? or if any ideas, feel free to discuss.

Thoughts?

**Comment by MorganNesbitt** [comment]
I faced two disappearing bugs. 1) from moving from anything after internal and 2) moving into the complete column.
The changes relative to the 1st HAVE TO STAY (These have nothing to do with complete column~ish).
As for the bug. Are you talking about the button that sends it from any todo column back to complete?

**Comment by allenduy** [comment]
Yeah, the button that shows the rewind symbol.

**Comment by lburkett** [comment]
So not sure we have the time to implement appending the description for the user, if they wanted to use a feature like this they can simply edit the description themselves prior to sending it back. I forgot to remove the lock when a card is sent back and I will update the features/server branch with this change.

**Comment by MorganNesbitt** [comment]
I think keeping a check mark would confuse users.

**Comment by allenduy** [comment]
When using it without a check mark, I was confused whether it worked or not.

**Comment by lburkett** [comment]
The checkmark for the lock should stay, but when a card is sent back it should remove the lock and the checkmark with it, correct?

**Comment by MorganNesbitt** [comment]
I was talking about when it's sent back. I'm a little confused overall with the conversation now though.

**Comment by allenduy** [comment]
Oh yeah of course, sending it back shouldn't leave it in that department. I'm also confused, haha

**Comment by lburkett** [comment]
Since some of these changes intersected with changes in features/server I have gone ahead and merged the two. I will close this pull request and we can now just refer to pull request #83 instead.

**Pull request closed without merging**
