### PR TITLE
Detail Department and Grant name

### LINKED ISSUE #73: Determine current department
Currently there is no way to determine what department you currently are on purely from the detail page.

This might prove confusing if you are an admin, trying to remember what page you are on.

### PR DESCRIPTION
**Pull request by MorganNesbitt**
Fixes #73 
# Summary
- Adds Department name to detail page
- Adds grant name to detail page

### CODE REVIEW

**Comment by lburkett** [comment]
So a couple things to think about before merging. Do you think this would look better left justified over centered? Do you think it would look better if located above the progress bar?

**Comment by MorganNesbitt** [comment]
it looks atrocious above the progress bar (Imo). Content just doesn't seem to work well above the progress bar.

I don't like left justified, but it's not really my decision.

**Comment by lburkett** [comment]
Fair enough, just some thoughts! Figured you had tried a bunch of different positioning, just curious to hear your opinions.

**Comment by MorganNesbitt** [comment]
Yeah, lol. People can experiment with it and give their thoughts too.

**Comment by allenduy** [comment]
What if we passed the details into the navbar method?

**Comment by lburkett** [comment]
Good point, this might be something to try and would result in a cleaner look to the detail page. My concern is changing the navbar for only the one view as it's supposed to be fairly static.

**Comment by MorganNesbitt** [comment]
I like the navbar as is

**Comment by lburkett** [comment]
At this point functionality over aesthetics. Just leave it for now, we can approach it again later.

**Pull request merged**
