### PR TITLE
Features/server

### PR DESCRIPTION
**Pull request by lburkett**
Add the locking system to the cards, not sure if we wanted to go further than this. I figured this was enough for ship, but if anyone sees any glaring errors/issues let me know!

### CODE REVIEW

**Comment by allenduy** [comment]
This doesn't actually lock the card in place, right? Just updates the array of booleans?

**Comment by lburkett** [comment]
Correct, all this does is edit the card object to lock it and update icons depending on its lock status.

**Comment by lburkett** [comment]
I have merged in features/department_navigation into this branch now since they coincided. Check this branch out and let me know if any other changes need to be made to get this working correctly.

**Comment by allenduy** [comment]
Card approval from Internal to ASU is bugged.

**Comment by MorganNesbitt** [comment]
I'm not sure if it was pulled into this one. But there was a server change I made that fixed that.

**Comment by MorganNesbitt** [comment]
Actually it is in here. 7b77b57 fixes that. What exactly happens?

**Comment by allenduy** [comment]
I'll try it again later to make sure it is bugged after a server restart, but it gives a completion check mark, but when I check the actual department, it's not there.

**Comment by allenduy** [comment]
Just tried it again, seems fine now!

**Pull request merged**
